name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  HUGO_VERSION: 0.147.8
  NODE_VERSION: 23
  GO_VERSION: 1.19
  CONTENT_PATH: "content"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # ===== 添加缓存步骤 =====
      - name: Cache Hugo modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/hugo
          key: ${{ runner.os }}-hugo-modules-${{ hashFiles('go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugo-modules-
            
      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      # ===== 缓存结束 =====
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm  # 与上面的缓存步骤配合使用

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: |
          hugo mod get -u
          hugo mod verify
          npm ci

      - name: Build site
        run: hugo --minify
        env:
          HUGO_ENV: production
          HUGO_BASEURL: ${{ 
            github.repository == format('{0}/{0}.github.io', github.repository_owner) 
              && format('https://{0}.github.io/', github.repository_owner)
              || format('https://{0}.github.io/{1}/', github.repository_owner, github.event.repository.name) 
          }}
          HUGO_CONTENT_DIR: ${{ env.CONTENT_PATH }}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true